name: Build bit7z for macOS

on:
    workflow_dispatch:
        inputs:
            bit7z_version:
                description: "bit7z版本 (如4.0.12) "
                required: true
                type: string

jobs:
    build-for-macos:
        runs-on: macos-latest
        steps:
            - name: Install packages (YASM for optimizations, p7zip for and only for test)
              run: brew install yasm p7zip

            - name: Download 7zip-zstd source code & extract & build 7-zip shared library
              run: |
                mkdir 7zip-build
                mkdir 7zip
                cd 7zip-build
                curl -L -o v26.01-v1.5.7-R1.tar.gz https://github.com/mcmilk/7-Zip-zstd/archive/refs/tags/v26.01-v1.5.7-R1.tar.gz
                tar -xzf v26.01-v1.5.7-R1.tar.gz
                cd 7-Zip-zstd-26.01-v1.5.7-R1/CPP/7zip/Bundles/Format7zF
                export SDKROOT=`xcrun --sdk macosx --show-sdk-path`
                export MACOSX_DEPLOYMENT_TARGET=13.3
                make -f makefile.gcc -j1 USE_ASM=1 ASM=yasm
                ls -la _o
                cd ../../../../../..
                cp 7zip-build/7-Zip-zstd-26.01-v1.5.7-R1/CPP/7zip/Bundles/Format7zF/_o/7z.so 7zip/7z.dylib
                cp 7zip-build/v26.01-v1.5.7-R1.tar.gz v26.01-v1.5.7-R1.tar.gz
                rm -rf 7zip-build

            - name: Download bit7z source code & extract
              run: |
                curl -LO "https://github.com/rikyoz/bit7z/archive/refs/tags/v${{ github.event.inputs.bit7z_version }}.tar.gz"
                tar -xzf v${{ github.event.inputs.bit7z_version }}.tar.gz
            
            - name: Prepare build environment & Run CMake configuration & compile
              run: |
                cd bit7z-${{ github.event.inputs.bit7z_version }}
                mkdir build
                cd build
                tar -xzf ../../v26.01-v1.5.7-R1.tar.gz
                SEVENZIP=$(realpath 7-Zip-zstd-26.01-v1.5.7-R1)
                cmake -S .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=13.3 -DBIT7Z_AUTO_FORMAT=ON -DBIT7Z_REGEX_MATCHING=ON -DBIT7Z_CUSTOM_7ZIP_PATH="$SEVENZIP" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBIT7Z_BUILD_TESTS=ON -B .
                echo cmake -S .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=13.3 -DBIT7Z_AUTO_FORMAT=ON -DBIT7Z_REGEX_MATCHING=ON -DBIT7Z_CUSTOM_7ZIP_PATH="$SEVENZIP" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBIT7Z_BUILD_TESTS=ON -B . > ../cmake-opts.txt
                cmake --build . -j 1 --config Release

            - name: Run test (optional)
              run: |
                cd bit7z-${{ github.event.inputs.bit7z_version }}/build
                ctest --output-on-failure -j1
              continue-on-error: true
            
            - name: Collect all targets
              run: |
                tar -czvf bit7z-${{ github.event.inputs.bit7z_version }}-macos.tar.gz \
                bit7z-${{ github.event.inputs.bit7z_version }}/include \
                bit7z-${{ github.event.inputs.bit7z_version }}/lib \
                bit7z-${{ github.event.inputs.bit7z_version }}/cmake-opts.txt \
                7zip

            - name: Upload Artifact (tar.gz)
              uses: actions/upload-artifact@v4
              with:
                name: bit7z-${{ github.event.inputs.bit7z_version }}-macos
                path: bit7z-${{ github.event.inputs.bit7z_version }}-macos.tar.gz

    release:
        runs-on: macos-latest
        needs: [build-for-macos]
        # 授予写入权限，允许创建 Release
        permissions:
          contents: write
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.bit7z_version != ''
        steps:
          - name: Download all artifacts
            uses: actions/download-artifact@v4
            with:
              path: ./artifacts

          - name: List downloaded files
            run: ls -la ./artifacts

          - name: Create GitHub Release and upload assets
            uses: softprops/action-gh-release@v2
            with:
              tag_name: bit7z-v${{ github.event.inputs.bit7z_version }}-macos
              name: Release bit7z-v${{ github.event.inputs.bit7z_version }}-macos
              body: |
                ## bit7z-${{ github.event.inputs.bit7z_version }}-macos

                ### 📦Download notice:
                  - [ ] **macOS**: `bit7z-${{ github.event.inputs.bit7z_version }}-macos.tar.gz`

                ### ✨Build environment:
                  - [ ] Newest macOS

                ### 🔧Contents
                - bit7z static library (`lib/x64/libbit7z.a`)
                - bit7z headers (`include/`)
                - 7-Zip shared library (`7z.dylib`)
              draft: false
              prerelease: false
              files: |
                ./artifacts/**/*.tar.gz
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}