name: Build bit7z

on:
    workflow_dispatch:
        inputs:
            bit7z_version:
                description: "bit7z版本 (如v4.0.12) "
                required: true
                type: string

jobs:
    build-for-manylinux_2_28:
        runs-on: ubuntu-latest
        container:
            image: quay.io/pypa/manylinux_2_28_x86_64
        steps:
            - uses: actions/checkout@v4
            - name: Install packages
              run: yum install -y tar wget

            - name: Download 7zip-zstd source code & extract & build 7-zip shared library
              run: |
                mkdir 7zip-build
                cd 7zip-build
                wget https://github.com/mcmilk/7-Zip-zstd/archive/refs/tags/v26.01-v1.5.7-R1.tar.gz
                tar -xzf v26.01-v1.5.7-R1.tar.gz
                cd 7-Zip-zstd-26.01-v1.5.7-R1
                cd

            - name: Download bit7z source code & extract
              run: |
                wget "https://github.com/rikyoz/bit7z/archive/refs/tags/${{ github.event.inputs.bit7z_version }}.tar.gz"
                tar -xzf ${{ github.event.inputs.bit7z_version }}.zip
            
            - name: Prepare build environment
              run: |
                cd bit7z-${{ github.event.inputs.bit7z_version }}
                mkdir build
                cd build
            
            - name: Run CMake configuration
              run: |
                cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBIT7Z_AUTO_FORMAT=ON -DBIT7Z_REGEX_MATCHING=ON